Set milestone

diff --git a/.github/workflows/daily.yaml b/.github/workflows/daily.yaml
--- a/.github/workflows/daily.yaml
+++ b/.github/workflows/daily.yaml
@@ -38,6 +38,11 @@ jobs:
       - name: Set timezone
         run: sudo timedatectl set-timezone "$TIMEZONE"
 
+      - name: Install GH milestones extension
+        run: gh extension install valeriobelli/gh-milestone
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+
       - name: Generate daily summary
         id: summary
         run: |
@@ -67,6 +72,29 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 
+      - name: Maybe set current year
+        if: ${{ steps.summary.outputs.text }}
+        run:
+          echo "CURRENT_YEAR=$(date '+%Y')" >> $GITHUB_ENV
+
+      - name: Maybe create milestone
+        if: ${{ steps.summary.outputs.text }}
+        run: |
+          milestones=$(gh milestone list --repo $SUMMARY_REPOSITORY)
+
+          if ! echo "$milestones" | grep -q "$CURRENT_YEAR"; then
+            echo "Milestone for $CURRENT_YEAR not found. Creating."
+            gh milestone create \
+               --title "$CURRENT_YEAR" \
+               --description "$CURRENT_YEAR contributions" \
+               --due-date $(date -d "$((CURRENT_YEAR+1))-01-01 -1 second" +"%F")  \
+               --repo "$SUMMARY_REPOSITORY"
+          else
+            echo "Milestone for $CURRENT_YEAR already exists. Skipping"
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+
       - name: Maybe post issue and lock
         if: ${{ steps.summary.outputs.text }}
         run: |
@@ -74,6 +102,7 @@ jobs:
             --title "Daily Summary of $(date -d 'yesterday' '+%Y-%m-%d')" \
             --body "${{ steps.summary.outputs.text }}" \
             --assignee "$SUMMARY_ASSIGNEE" \
+            --milestone "$CURRENT_YEAR" \
             --label summary | grep -o 'https://github.com[^ ]*')
 
           gh issue lock "$ISSUE_URL"
@@ -87,6 +116,7 @@ jobs:
             --title "No summary available for $(date -d 'yesterday' '+%Y-%m-%d')" \
             --body "No summary available." \
             --assignee "$SUMMARY_ASSIGNEE" \
+            --milestone "$CURRENT_YEAR" \
             --label no-summary | grep -o 'https://github.com[^ ]*')
 
           gh issue lock "$ISSUE_URL"
